---
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
script:
  - mvn verify -B -Drelease=false
cache:
  directories:
    - $HOME/.m2/repository
after_success:
  - bash <(curl -s https://codecov.io/bash)